name: Deploy Simple

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Timeout totale di 10 minuti
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: |
        cd siw-watch_shop
        mvn clean package -DskipTests
        
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        timeout: 300s
        script: |
          # Test connessione
          echo "Connesso a EC2!"
          
          # Stop processo esistente
          sudo pkill -f "siw-watch_shop" || echo "Nessun processo da fermare"
          sleep 3
          
          # Pulisci file vecchi
          rm -f siw-watch_shop-*.jar
        
    - name: Copy JAR only
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        timeout: 120s
        source: "siw-watch_shop/target/siw-watch_shop-1.0.jar"
        target: "/home/ubuntu/"
        
    - name: Start Application
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        timeout: 60s
        script: |
          # Avvia app
          cd /home/ubuntu
          nohup java -jar siw-watch_shop/target/siw-watch_shop-1.0.jar > app.log 2>&1 &
          
          # Attendi 5 secondi
          sleep 5
          
          # Verifica se è partita
          if pgrep -f "siw-watch_shop" > /dev/null; then
            echo "App avviata con successo"
          else
            echo "Errore nell'avvio"
            tail -10 app.log
          fi